version: '3.4'

services:
  bemol.app:
    image: ${DOCKER_REGISTRY-}bemolapp
    build:
      context: .
      dockerfile: src/bemol.App/Dockerfile
    environment:
        DBServer: "db"
    ports:
     - "8000:80"
    depends_on:
     - db
     - rabbitmq
    networks:
     - net

  bemol.consumerMessage:
    image: ${DOCKER_REGISTRY-}bemolconsumermessage
    build:
      context: .
      dockerfile: src/bemol.ConsumerMessage/Dockerfile
    depends_on:
     - rabbitmq
    networks:
     - net

  db:
    image: luizcarlosfaria/mssql-server-linux:latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Gus123456
      - MSSQL_PID=Developer
      - MSSQL_DATABASE=bemolDatabase
      - MSSQL_USER=gus
      - MSSQL_PASSWORD=Gus654321
    ports:
      - "14331:1433"
    volumes:
      - sql_data:/var/opt/mssql/data 
    networks:
      - net

  rabbitmq:    
    image: rabbitmq:3-management
    ports:
    - "15672:15672"  #Management
    - "5672:5672"    #AMQP
    environment:
      RABBITMQ_DEFAULT_USER: mc
      RABBITMQ_DEFAULT_PASS: mc2
      RABBITMQ_DEFAULT_VHOST: main
    volumes:
      - mq_data:/var/lib/rabbitmq/mnesia
    networks: 
     - net

volumes:
  mq_data:
  sql_data:
    driver: local

networks:
  net:
    driver: bridge

